### ISSUE TITLE
Longer queue select / deselect responsiveness is poor

### ISSUE THREAD

**Issue by isaachinman** [isaachinman/wundershine-native-app#115]
**Describe the bug**
From Mick:

> This is probably difficult/impossible to improve now, but with longer queues there is also a multi second lag with select / deselect.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by isaachinman** [comment]
@Tintels I need your help on this one. Can you please provide some information as to how we can reproduce the problem (including demo accounts), and possibly a video of the delay happening?

**Comment by isaachinman** [comment]
So, this actually comes down to Mongoose/MongoDB write speed. It turns out that the entire queue data structure is being written for each selection/deselection action.

For the bo@bo.nl account, there were 47 images in the deselected array, amounting to ~29kb of data being written with each action.

**Comment by isaachinman** [comment]
I've spent about 2 hours working on query optimisation. I am going to push this to the beta API and do some real-world testing, but there's an overwhelming chance what we're discussing here is premature optimisation.

**Comment by isaachinman** [comment]
This should be now fixed, with a combination of native and API performance enhancements.

**Comment by isaachinman** [comment]
3a3af7a

**Comment by Tintels** [comment]
Great stuff!
