### ISSUE TITLE
Orders page overlap

### ISSUE THREAD

**Issue by isaachinman** [isaachinman/wundershine-native-app#116]
**Describe the bug**
From Mick:

> I have an older note that the Your Orders page has overlapping / messy lay out when there are multiple historic orders. Did not re-check.

**To Reproduce**

**Expected behavior**

**Screenshots**

**OS (please complete the following information):**

**Additional context**

**Comment by isaachinman** [comment]
@Tintels I need your help on this one. Can you please provide some information as to how we can reproduce the problem (including demo accounts), and possibly a video of the delay happening?

**Comment by isaachinman** [comment]
Ah, good catch. That is related to my recent Instagram work and the bug is only present in beta. Thanks.

**Comment by Tintels** [comment]
Perhaps when it's fixed you can creat an account with multiple past orders and post the login here? We can check layout acceptability together.

**Comment by isaachinman** [comment]
Sure. The login details are: isaac@isaachinman.com / blue

Here's a screenshot:

<img width="538" alt="screenshot 2018-10-04 at 10 27 44" src="https://user-images.githubusercontent.com/10575782/46465324-37495080-c7c0-11e8-8189-f0be6fad64f4.png">

Looks fine to me, but maybe I misunderstood?

**Comment by Tintels** [comment]
Yes. I  must have made the note too long ago ..
