### ISSUE TITLE
Flash grid visibility on screen load on EditImage

### ISSUE THREAD

**Issue by isaachinman** [isaachinman/wundershine-native-app#117]
**Is your feature request related to a problem? Please describe.**
It might not be clear to all users that the image on the EditImage screen is pannable/zoomable. We'd like to flash the editing grid UI briefly upon page load to make this clear.

**Describe the solution you'd like**
Flash grid visibility for some short duration on screen load.

**Describe alternatives you've considered**
N/A.

**Additional context**
The [EditImage screen is here](https://github.com/isaachinman/wundershine-native-app/blob/master/src/screens/private/EditImage/EditImage.js). Will most likely need to add a hook in `componentDidMount`.

**Comment by isaachinman** [comment]
ebce059

**Comment by Tintels** [comment]
Flash should also start when/after the grey placeholder is replaced with image. In some slower cases the flash is (only) visible on top of grey block..

**Comment by isaachinman** [comment]
07917e1
