### ISSUE TITLE
Credit card payment failure

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-native-app#121]
**Describe the bug**
Modal with credit card details and validation seems to work, but then on payment method screen, the card is missing.

**To Reproduce**

Attempt for real order on production app with real VISA card. 
1. Go to Payment method
2. Click on credit card'
3. Enter details. The modal seems to chake and validate the data. Tap done
4. Card does not appear on paayment method screen

**Expected behavior**
Card appears on payment method screen

**Screenshots**

**OS (please complete the following information):**
 - Device: [Nexus 5X]
 - OS: Android

**Additional context**

**Comment by Tintels** [comment]
Test result: Card appears on payment method screen. 
Complete order fails.

**Comment by Tintels** [comment]
Update / additional info for deduction: I tried to process an order using a discount code and the order did not process that way either.

**Comment by isaachinman** [comment]
I don't understand these bug reports. Can you explain to me what you mean, and perhaps include screenshots?

I just made a credit card order via the app. Everything was successful - Wundershine order created, Shopify order created, Stripe charged card successfully. I am not able to see a HH order via their web UI, but that's not working for our staging orders either.
