### ISSUE TITLE
Some API / dns failure reported by Ruud - Don't know if this is a bug

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-native-app#126]
**Describe the bug**
A log file produced by Ruud after a print test order showed a failure which he characterised as "probably a dns mistake" The log file text is at the bottom of this post.

I also saw a re-appearance of issue #120. This is probably related.

The relevant order with images transfer seems to be succcesful both in Shopify and the HH back end. 

**To Reproduce**
1. Order 5 pack
2. Check system log

**OS (please complete the following information):**
 - Device: [Nexus 5X]
 - OS: [Android 8.1]

**Additional context**

Test order LOG File

Wundershine [NOTIFY] 5c7d35b75facb400203625de
Request
https://api.wundershine.com:443/v1/admin/huighaverlag/order/5c7d35b75facb400203625de/status?secret=7bae7c52-feaa-4071-826e-d8f00f0e2d14
Parameters
{
  "secret": "7bae7c52-feaa-4071-826e-d8f00f0e2d14",
  "customer": "#13:10",
  "order": "5c7d35b75facb400203625de",
  "status": "GENERATED",
  "timestamp": 1551709642776
}
Payload
{
  "timestamp" : 1551709642776,
  "status" : "generated"
}
Response
FAILED
Future{cause=Search domain query failed. Original hostname: 'https://api.wundershine.com' failed to resolve 'https://api.wundershine.com.huighaverlag.nl' after 3 queries }

**Comment by isaachinman** [comment]
@Tintels I'm going to need more information. Who is calling https://api.wundershine.com.huighaverlag.nl? That's not a valid URL.

**Comment by Tintels** [comment]
That log file was send to me by Ruud in an email. Probably it's best you take it up directly with him. The test order was on Monday.

Cheers

**Comment by isaachinman** [comment]
From Ruud:

> It turned out that it was caused by an API change in the Vertx webclient module and wrong credentials. 
> I managed to mark the last order as 'processed'.
